### ISSUE TITLE
Implement grades distribution for GraphQL

### ISSUE THREAD

**Issue by ramanxg** [icssc-projects/peterportal-public-api#14]
Currently implemented in REST.

It should be helpful to check out these files for how it is implemented in REST.

/rest/v0/grades.helper.js
/rest/v0/grades.js

We would need it for both calculated and raw grades.

GraphQL endpoint that can filter for a certain class:

```
{
  grades(year:"2018-19", instructor:"PATTIS, R.") { // here is it possible to add multiple arguments
    year
    quarter
    department
    ...
  }
}

**Comment by ChaseC99** [comment]
Looking for input on how to implement this. Sorry in advance for the long comment LOL

Each `grade_distribution` has a corresponding `course_offering` (_new object that will also be used for schedules later on - not sure if "courseOffering" is the best name for it_)  

We could image a `grade_distribution` object and its `course_offering` to look something like this:
```graphql
grade_distribution {
  gradeACount, gradeBCount, gradeCCount, gradeDCount, gradeFCount, gradePCount, gradeNPCount, gradeWCount, averageGPA,
  
  course_offering {
    year, quarter, code, section, type,
    instructor { ... },
    course {
      id, department, number, ...
    }
    grade_distribution { ... }
  }

}
```

The `grades` query would return a `grade_distribution_collection`, which returns a list of `grade_distribution` objects and an aggregated summary.

```graphql
grade_distribution_summary {
  summary {
    sumGradeACount, sumGradeBCount, ..., grade_distribution_count
  }

  grade_distributions <- [grade_distribution]
}
```

In addition, it would make sense for each professor/course to have a `grade_history` field, which is a `grade_distribution_summary` object.


## Questions I have for you guys: 
1. How do we feel about the proposed schema? Open to suggestions
2. Can we change the REST api fields to underscore casing? So `gradeACount` -> `grade_a_count` (or even just `a_count`). Everything else is underscore, so we should stay consistent.
3. Why do we have a `/grades/calculated` endpoint when the client could compute that info? If we don't need the summation stats, that would simplify this query a lot. I'm a little confused since I don't know how clients like Zotistics use this endpoint.
4. Additional thoughts on anything else?

**Comment by ramanxg** [comment]
## A couple thoughts on the questions you had
1. (4 as well) I was also thinking about this for the REST endpoints as well. I believed that for users if they want the grade distribution, they would almost always compute the calculated statitistics from all the courses found. For example in zotistics, how it works is the user queries a professor, department, course, etc. and then displays a histogram of counts of grades for all the courses together. I'm not sure of a use case to have the list of courses without an aggregate computation, which is why we just do it anyways to save the client for more effort.
 
2. For the `grade_distribution` object, I saw that `course_offerring` also has a `grade_distribution` field. What exactly would be stored in this, since the overall `grade_distribution` object already has the grade statistics, or is this the `grade_history` object mentioned? Another question I have is what would be stored in the `grade_distribution_summary` object for each course/professor if these numbers are already in the bigger grade_distribution object.

3. I definitely agree with this, they should all be consistent. I think having `grade_a_count` is better than `a_count` just since it's more clear.

**Comment by ChaseC99** [comment]
## 1
Ok that makes sense. We can move forward with a `grade_distribution_collection` then.

## 2
Sorry `grade_distribution_summary` was a typo, I meant `grade_distribution_collection` (I've gone through a lot of names trying to find one that makes sense hahaha). 

Yes, `grade_distribution` has a reference to `course_offering`, which has a reference back to `grade_distribution`. Obviously it doesn't make sense to do this from the grades query. But if the user gets to a `course_offering` object through a professor's `course_history` then that user should be able to access the corresponding `grade_distribution`.

`grade_history` is just the field (variable) name for a professor or course's previous grades. This would be a `grade_distribution_collection` object. The thought is, instead of using the grades query, you could could query by course/professor to get their grade information. For example:
```graphql
{
  course(id: "COMPSCI161") {
    grade_history {
      aggregate { avg_gpa, count }
    }
  }
}
```
## 3
Yeah, `grade_a_count` is more clear. I'll use this.

**Comment by nananananate** [comment]
> Yes, grade_distribution has a reference to course_offering, which has a reference back to grade_distribution. Obviously, it doesn't make sense to do this from the grades query. But if the user gets to a course_offering object through a professor's course_history then that user should be able to access the corresponding grade_distribution.

This is exactly how I'd imagine it too! My fear is, as we are using the current cache, query time is going to up. 

Also, assuming `course_offering` is implemented later, I think this is what we can work on:
* `grade_distribution`
* `grade_distribution_collection`  
* `grade_history` for `professor` and `course`  
* `grades` endpoint returning a `grade_distribution_collection`  

My worry right now is query time for `grade_history`. Especially with a list of `course` or `professor`, there would need to be an individual query of a `grade_distribution_collection` for each one. I'm getting on a tangent now, but thinking about the future, we'd really benefit from a centralized remote database, like Firebase. But also I'm partial to SQL, but idk of a Firebase equivalent for it (besides AWS RDS).

**Comment by ChaseC99** [comment]
That's a really good point. `grade_history` would be super inefficient when computing for a list of courses.... ideally we wouldn't have to send separate sql queries for each course.

We should sync up to think about how to best implement `grade_history`.

In the meantime though, I'll get started on the regular grades query. That one shouldn't be as complicated.
