### ISSUE TITLE
Create Instructor Name Map

### ISSUE THREAD

**Issue by ChaseC99** [icssc-projects/peterportal-public-api#53]
For some queries, like `grades` and `schedule`, the instructor name (e.g. "PATTIS, R.") is returned instead of the ucinetid. As a result, we are unable to connect that instructor field with the instructor type.

To fix this, we should create a dictionary that maps the instructor name to their ucinetid.

**Comment by ramanxg** [comment]
Taking a look, and I noticed for the common names especially, some instructors have the same ("LAST, F"). Since it's not unique for professors. Especially true for common names like (SMITH, J.). I'm not sure of another solution besides mapping the instructor name to an array of ucinetids that matter. Then in GraphQL the instructor would be an array of instructors.

What are your thoughts on this?

**Comment by ChaseC99** [comment]
Per our conversation: return list of all possible ucinetids. 

Given the list, we'll do our best to determine the correct instructor using departments/course history. Worst case scenario, GraphQL returns an error stating that it can't determine the instructor.
